name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  GITHUB_TOKEN:  # id of input
    description: 'GitHub Auth token'
    required: true
  RELEASE_VERSION:  # id of input
    description: 'Release version'
    required: true
  FINALISE_RELEASE:  # id of input
    description: 'Y/N to create release tags'
    required: true
    # default: 'World'
runs:
  using: 'node12'
  main: './dist/index.js'