name: 'Release Creator'
description: 'Will loop over Skedify repos & create release branches/trigger stable release'
inputs:
  release-name:  # id of input
    description: 'Release version'
    required: true
  finalize-release:  # id of input
    description: 'Y/N to create stable release tags'
    required: true
    default: 'N'
runs:
  using: 'node12'
  main: './dist/index.js'