name: 'Aggregate Release Notes'
description: ''

inputs:
  cursorFile:
    description: 'The cursor file.'
    default: changelog-cursor.json
  releaseNoteRepo:
    description: 'The release Notes Repo'
    default: releases
  basePath:
    description: 'Base path of the releases project'
    default: ""
  mainBranch:
    description: 'Main branch of the releases project'
    default: "main"

runs:
  using: "node24"
  main: './dist/index.js'
