name: 'AI Translator'
description: ''

inputs:
  repo:
    description: 'Repo to translate'
  prBranch:
    description: 'PR branch of the to be translated project'
    default: "main"
  mainBranch:
    description: 'Main branch of the repo'
    default: "develop"

runs:
  using: "node24"
  main: './dist/index.js'
