name: Aggregate Release Notes
on:
  workflow_dispatch:

jobs:
  aggregate-release-notes:
    name: Aggregate release notes
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Aggregate release notes
        uses: ./aggregate-release-notes # Uses an action in the root directory
        env:
          # Use SKEDIBOT_PAT so it can trigger deploy actions from running.
          GITHUB_TOKEN: ${{ secrets.SKEDIBOT_PAT }}
          GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}
        with:
          cursorFile: changelog-cursor.json
