name: Release Creator
on:
  workflow_dispatch:
    inputs:
      release-name:
        description: 'Release tag'
        required: true
      finalize-release:
        description: 'Finalize release (Y/N)'
        required: false
        default: 'N'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create releases on repo's
        uses: ./release-creator # Uses an action in the root directory
        env:
          GITHUB_TOKEN: ${{ secrets.SKEDIBOT_PAT }}
        with:
          release-name: ${{ github.event.inputs.release-name  }}
          finalize-release: ${{ github.event.inputs.finalize-release  }}
